/**
 * `npm run setup` — writes .env.local for local development (embedded Postgres, console mail).
 * Never overwrites an existing file. Production values come from your host's env settings.
 */
import { randomBytes } from "node:crypto";
import { existsSync, writeFileSync } from "node:fs";
import path from "node:path";
import { DEV_CLUSTER, localUrls, ROOT } from "./lib/local-db";

const file = path.join(ROOT, ".env.local");
if (existsSync(file)) {
  console.log(".env.local already exists — leaving it untouched.");
  process.exit(0);
}

const urls = localUrls(DEV_CLUSTER);
writeFileSync(
  file,
  `# Generated by \`npm run setup\` — local development only. Never commit this file.
APP_URL=http://localhost:3000

# Runtime connection (non-superuser, NOBYPASSRLS role) -> embedded Postgres from \`npm run db:dev\`
DATABASE_URL=${urls.app}
# Used only by migration scripts
DATABASE_OWNER_URL=${urls.owner}

BETTER_AUTH_SECRET=${randomBytes(32).toString("base64")}

# Dev mail prints verification / reset links in the terminal running \`npm run dev\`.
MAIL_TRANSPORT=console
# Lets \`npm run build\` / \`npm run start\` run locally with console mail. Production refuses
# non-Resend mail without this flag — NEVER set it in a deployed environment.
ALLOW_DEV_MAIL=true
`,
);
console.log("Created .env.local");
